# -*- coding: utf-8 -*-
"""Sentiment.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1OrGJ4jf4PVvoJtXw9mhp-nn4hPwH9b7J
"""

######## IMPORT THE LIBRARIES 

import requests

import numpy as np
import time, datetime, threading
from bs4 import BeautifulSoup
from nltk.sentiment import SentimentIntensityAnalyzer
import nltk
nltk.download('all')
from datetime import datetime, date
from gensim.models import Word2Vec
import sys

analyser = SentimentIntensityAnalyzer()

############ IMPORT THE WEBSITES

r = requests.get("https://www.forexfactory.com/#closed")
url = "https://www.forexlive.com/feed/news"
url2 = 'https://finance.yahoo.com/quote/GC=F?p=GC=F'
url3 = "https://www.reuters.com/news/archive/businessnews?view=page&page=2&pageSize=10"

resp = requests.get(url)
r2 = requests.get(url2)
r3 = requests.get(url3)

bsoup = BeautifulSoup(resp.content, features='xml')
soup = BeautifulSoup(r.text, 'lxml')
ssoup = BeautifulSoup(r2.text, 'lxml')
print(len(ssoup))
soup3 = BeautifulSoup(r3.text, 'lxml')

goldPrice = ssoup.findAll("div", class_='My(6px) Pos(r) smartphone_Mt(6px)')[2].find_all('p').text
items = bsoup.findAll('item')
table = soup.find("table", class_="calendar__table")
reutersdivs = soup3.find("div", class_="news-headline-list ")
reutersdivs = soup3.findAll("article", class_='story')

today = date.today()